#pragma once
//third-pary
#include "OPEEngine.h"
//in-house
#include "ButtonDriver_types.h"

// clang-format off
class Device
{
    public:

        /*USER CODE: instantiate data containers here:*/

        opee::DataWatch<ButtonEvent, 80, 3> usr_button; // type: custom (event generated by button), total callback storage: 48 bytes, max subscribers: 2

        /*USER CODE: end*/

        Device(): 

            /*USER CODE: instantiate data objects with initial values:*/

            usr_button(ButtonEvent::uninit) // initial value of uninitialized
            
            /*USER CODE: end*/
        {
        }
};

// clang-format on